Update prod-build-publish.yml
added erroring if curl request returns 400> and verbose logging on curl

diff --git a/.github/workflows/prod-build-publish.yml b/.github/workflows/prod-build-publish.yml
--- a/.github/workflows/prod-build-publish.yml
+++ b/.github/workflows/prod-build-publish.yml
@@ -46,7 +46,11 @@ jobs:
         projects: "docamatic"
          
     - name: Chrome Webstore Access Token
-      run: ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${{secrets.CHROME_WEBSTORE_CLIENT_ID}}&client_secret=${{secrets.CHROME_WEBSTORE_CLIENT_SECRET}}&refresh_token=${{secrets.CHROME_WEBSTORE_REFRESH_TOKEN}}&grant_type=refresh_token" | jq '.access_token') >> $GITHUB_ENV
+      run: |
+        ACCESS_TOKEN=$(curl --fail-with-body -v "https://accounts.google.com/o/oauth2/token" -d "client_id=${{secrets.CHROME_WEBSTORE_CLIENT_ID}}&client_secret=${{secrets.CHROME_WEBSTORE_CLIENT_SECRET}}&refresh_token=${{secrets.CHROME_WEBSTORE_REFRESH_TOKEN}}&grant_type=refresh_token" | jq '.access_token') >> $GITHUB_ENV
+        if [ $? -ne 0 ]; then \
+          echo "::error access token::Unable to get access token" \
+        fi
     
     - name: Chrome Webstore Publish
       run: |
